linked the header properly from doc page
Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE- pull request #1051
Opened 2024-07-27 13:31 UTC by lolpanda2004

## Description

Fixed the link from the doc page and made the link connect to proper html code and redesigned it from a button to a natural looking header name like other tags

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes 1050

## Type of PR

- [ X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [X ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ X] I have updated my branch and synced it with project `main` branch before making this PR
- [X ] I have performed a self-review of my code
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

2024-07-27 14:45 UTC, lolpanda2004 commented
@varshith257 Please assign this issue and review my PR! Thank you.

2024-07-27 15:05 UTC, varshith257 requested changes
Could you follow up with this suggestion?

2024-07-27 15:05 UTC, varshith257 commented on Html-Files/Doctor Experience.html
> +        <a href="../dex.html" style="color: #ecf0f1;">Service</a>
```suggestion
        <li><a href="../dex.html" style="color: #ecf0f1;">Service</a></li>
```

2024-07-27 15:35 UTC, lolpanda2004 commented on Html-Files/Doctor Experience.html
> +        <a href="../dex.html" style="color: #ecf0f1;">Service</a>
Done!

2024-07-28 04:53 UTC, lolpanda2004 commented
I completed please do check @varshith257

2024-07-28 05:19 UTC, merged