added changes to login signup page
Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE- pull request #1162
Opened 2024-08-08 17:24 UTC by DiwareNamrata23

## Description

## Related Issues

- Closes #660 

## Type of PR

- [ ] ()

## Screenshots / videos (if applicable)

<img width="1440" alt="Screenshot 2024-08-08 at 10 54 22 PM" src="https://github.com/user-attachments/assets/f5999dfe-9d12-4d9b-840f-1f58c446fc54">
<img width="1440" alt="Screenshot 2024-08-08 at 10 54 30 PM" src="https://github.com/user-attachments/assets/9e863c5b-fb0b-41a1-908d-ac4e39afcd19">

## Checklist

- [ ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have performed a self-review of my code
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

2024-08-08 17:26 UTC, DiwareNamrata23 commented
@varshith257 removed conflicts

2024-08-08 19:03 UTC, varshith257 commented on index.html
> +        <li><a href="login.html"><i class="bi bi-box-arrow-right"></i> Sign in/Sign up</a></li>
```suggestion
        <li><a href="log/login.html"><i class="bi bi-box-arrow-right"></i> Sign in/Sign up</a></li>

```

2024-08-08 19:04 UTC, varshith257 commented
Also align footer with the home page one

2024-08-09 06:52 UTC, DiwareNamrata23 commented
Plz merge my pr

2024-08-09 15:20 UTC, DiwareNamrata23 commented
@varshith257 now there are no conflicts plz merge my pr

2024-08-09 15:28 UTC, varshith257 commented
@DiwareNamrata23  In deploy the page is misaligned. Have a look

2024-08-09 15:34 UTC, DiwareNamrata23 commented
Hi @varshith257 can you plz elaborate where is the issue

2024-08-09 15:35 UTC, varshith257 commented
> ### <span aria-hidden="true">✅</span> Deploy Preview for *rapidoc* ready!
> 
> 
> |  Name | Link |
> |:-:|------------------------|
> |<span aria-hidden="true">🔨</span> Latest commit | 30c407077222b97d5a70386ddfcb974b49d7b583 |
> |<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/rapidoc/deploys/66b591c36a3c150008c3fa3d |
> |<span aria-hidden="true">😎</span> Deploy Preview | [https://deploy-preview-1162--rapidoc.netlify.app](https://deploy-preview-1162--rapidoc.netlify.app) |
> |<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />![QR Code](https://app.netlify.com/qr-code/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJodHRwczovL2RlcGxveS1wcmV2aWV3LTExNjItLXJhcGlkb2MubmV0bGlmeS5hcHAifQ.hOTA83hm8TQWhATIT67jnQgFN8Wlc6s4zmNBcAK4g18)<br /><br />_Use your smartphone camera to open QR code link._</details> |
> ---
> 
> _To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/rapidoc/configuration/deploys#deploy-notifications)._

Here

2024-08-09 15:45 UTC, DiwareNamrata23 commented
@varshith257 can we have a quick google meet?

2024-08-09 15:55 UTC, varshith257 commented
> @varshith257 can we have a quick google meet?

Sure

2024-08-09 15:57 UTC, DiwareNamrata23 commented
To join the video meeting, click this link: https://meet.google.com/byb-bhic-eia
Otherwise, to join by phone, dial +1 336-365-5804 and enter this PIN: 209 873 779#

2024-08-10 06:18 UTC, varshith257 requested changes

2024-08-10 06:18 UTC, varshith257 commented on log/script.js
> -  // successBanner.id = "successBanner";
Why JS Code has been deleted?

2024-08-10 10:50 UTC, DiwareNamrata23 commented
@varshith257 is it working good now ?

2024-08-10 17:10 UTC, varshith257 commented
@Anjaliavv51 Once verify it

2024-08-10 17:15 UTC, Anjaliavv51 commented
@DiwareNamrata23 please check the deployment in netlify , their is gap between the sub footer section in footer tag and also the login container is overflowed.


![Screenshot_20240810_224310_Chrome](https://github.com/user-attachments/assets/afbf7572-ce97-4e3e-b8ef-9848b2f827f8)

2024-08-10 17:17 UTC, Anjaliavv51 commented
@varshith257 my suggestion is that their is no need of header and footer to the login page.

2024-08-10 17:17 UTC, Anjaliavv51 requested changes
@DiwareNamrata23 please check the deployment in netlify , their is gap between the sub footer section in footer tag and also the login container is overflowed.


![Screenshot_20240810_224310_Chrome](https://github.com/user-attachments/assets/afbf7572-ce97-4e3e-b8ef-9848b2f827f8)

2024-08-10 17:20 UTC, Anjaliavv51 commented
@varshith257 my suggestion is that their is no need of header and footer to the login page.

The current login page looks great , I this issue and PR need to be closed.

2024-08-15 11:27 UTC, closed without merging