Fixes #694
Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE- pull request #720
Opened 2024-06-28 09:22 UTC by puneet426

## Description

[Please include a brief description of the changes or features added]

##694

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #694

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist

- [ ] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [ ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have performed a self-review of my code
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

2024-06-30 18:02 UTC, varshith257 requested changes

2024-06-30 18:02 UTC, varshith257 commented on index.html
> +                <a href="/- fonts.txt" target="_blank">
@puneet426 Update links with previous ones used

2024-06-30 18:07 UTC, puneet426 commented on index.html
> +                <a href="/- fonts.txt" target="_blank">
okk

2024-06-30 18:14 UTC, puneet426 commented on index.html
> +                <a href="/- fonts.txt" target="_blank">
done

2024-06-30 18:15 UTC, puneet426 commented
please add level GSSOC

2024-06-30 18:17 UTC, varshith257 commented on index.html
> +              <a href="https://www.linkedin.com" target="_blank">
here too

2024-06-30 18:32 UTC, puneet426 commented on index.html
> +              <a href="https://www.linkedin.com" target="_blank">
here both links are same as previous

2024-07-04 15:22 UTC, varshith257 approved these changes

2024-07-04 15:22 UTC, merged