restyled news page
Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE- pull request #842
Opened 2024-07-12 21:08 UTC by samarsajad

## Description

Redesigned news page as per the theme of the website,added picture slider to make it attractive, added functionality to read more

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #714 

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/2beab93c-71d8-4f50-90ed-d071cd54714e

## Checklist

- [x] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have performed a self-review of my code
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
GSSoC'24

2024-07-12 21:09 UTC, samarsajad commented
Please review my pull request @varshith257 @Anishkagupta04

2024-07-15 07:27 UTC, samarsajad commented
Please review my pull request @varshith257

2024-07-16 18:21 UTC, samarsajad commented
Kindly take a look @varshith257

2024-07-16 20:11 UTC, varshith257 commented
@samarsajad Fix merge conflicts

2024-07-16 20:15 UTC, samarsajad commented
> @samarsajad Fix merge conflicts

Done @varshith257

2024-07-16 20:21 UTC, varshith257 commented
@samarsajad Looks good to merge after fixing this suggestions:

Make sure all readme buttons
 be center at each card 

Duplicate navbars resulted. Fix it

2024-07-17 05:47 UTC, samarsajad commented
> @samarsajad Looks good to merge after fixing this suggestions:
> 
> Make sure all readme buttons be center at each card
> 
> Duplicate navbars resulted. Fix it

I did a thorough screening of my code but I couldn't find anything related to duplicate nav bar. In fact in my local system the duplicate nav bar is not showing at all so I couldn't even use the inspect tool. Please help me out with this @varshith257

2024-07-17 06:19 UTC, varshith257 commented
![IMG_20240717_114911.jpg](https://github.com/user-attachments/assets/4c111524-95ab-457f-b70c-e0c514b27494)

See here

2024-07-17 06:24 UTC, samarsajad commented
> ![IMG_20240717_114911.jpg](https://private-user-images.githubusercontent.com/117595548/349382701-4c111524-95ab-457f-b70c-e0c514b27494.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTc2MTAsIm5iZiI6MTcyMTE5NzMxMCwicGF0aCI6Ii8xMTc1OTU1NDgvMzQ5MzgyNzAxLTRjMTExNTI0LTk1YWItNDU3Zi1iNzBjLWUwYzUxNGIyNzQ5NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwNjIxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTMyM2RiYzQwOTQzODMwOTA1MmI2YmM5MDc1MjY0NmQ0ZjE3OGJiZWJkMjQxNzQ1NzkzY2NkMDNjZGQ4MDA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sl-_b4hsBPZgJVYuduvNBOYU3NEJBlpeCZf2N-IvJCo)
> 
> See here

IK it is in the deploy preview but not in my local system. Even if i try fixing it, I wouldn't know if it is fixed cause this is not visisble in my local system. If you could merge this pull request and if the duplicate nav bar appears in the main, I'd raise a new issue for that cause as if now i am not able to fix this

2024-07-17 06:26 UTC, varshith257 requested changes

2024-07-17 06:26 UTC, varshith257 commented on news.html
> +  <link rel="stylesheet" href="../Css-Files/news.css">
Remove this line.Line 11 has same code

2024-07-17 06:26 UTC, varshith257 commented on news.html
>          <nav class="nav_menu">
Here's the duplicate code. See from line 422 to down has navbar code again same as above.

2024-07-17 06:28 UTC, varshith257 commented
Also align hover me button center to card and make sure not stick with image

2024-07-17 08:14 UTC, samarsajad commented
i will create a new pull request. things got a lil messed up @varshith257

2024-07-17 08:14 UTC, closed without merging

2024-07-21 14:53 UTC, samarsajad commented
created a new pull request #961  ptal @varshith257