Applied Color Grading and Adde Patient Testimonial Text
Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE- pull request #876
Opened 2024-07-15 11:11 UTC by RadhikaMalpani1702

## Description
Hey @varshith257 

I have Applied Color Grading and added Patient Testimonial Text.

![image](https://github.com/user-attachments/assets/1f3b52d9-98a8-41a9-9faa-5deefb8cc5c5)
![image](https://github.com/user-attachments/assets/e174ba16-fffd-4de2-bd17-c920bd684c1b)
![image](https://github.com/user-attachments/assets/7db92e04-0660-43cd-8d46-5b165040ffc7)
![image](https://github.com/user-attachments/assets/a01c2e08-2f18-45fa-8036-7cb5aa9fcd48)
![image](https://github.com/user-attachments/assets/b53dc458-befc-4c75-9e03-647575bcce34)
![image](https://github.com/user-attachments/assets/97d9498d-a987-41be-b6f1-01fa14bee6cc)

## Related Issues

- Closes #827 

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

2024-07-16 18:48 UTC, varshith257 requested changes

2024-07-16 18:48 UTC, varshith257 commented on index.html
> +          <h2 style="color: white;">Make an Appointment</h2>
```suggestion
          <h2 style="color: white;">Make an Appointment</h2>
L
```

Can this be moved to Css? Hardcoded color tag in index.html couldn't be good

2024-07-17 08:32 UTC, RadhikaMalpani1702 commented
@varshith257 I have done the changes please merge this PR

2024-07-18 13:42 UTC, RadhikaMalpani1702 commented
@varshith257 Please merge this PR

2024-07-18 13:47 UTC, varshith257 commented
@Anjaliavv51 @Pruthaa17 @aditya-bhaumik Have a look on this too

2024-07-18 13:59 UTC, aditya-bhaumik commented
@varshith257 hi i think this pull request can be merged

2024-07-18 14:00 UTC, aditya-bhaumik approved these changes

2024-07-18 14:00 UTC, Anjaliavv51 commented
@varshith257 this PR can be merged , all changes are done.

2024-07-18 14:02 UTC, varshith257 approved these changes

2024-07-18 14:03 UTC, merged